dist: xenial
language: python
cache: pip

matrix:
  include:
    - python: "3.7"
      env: PYTHONVER=3

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - graphviz
  homebrew:
    update: true
    packages:
      - python
      - graphviz
      - python2

install: 
  - python3 -m pip install -e .[dev]

script: make test

after_success:
    - codecov --token 7c3b60a8-46be-4bb2-b5ea-67e26b45ecbc

branches:
  only:
  - master

notifications:
  email: false
